--- insert here info about Textures descibed in resourses: GUI\Textures\!Textures

function get_Textures()

	return {
	{ name = "AddGreenNormal", sizeX = nil, sizeY = nil },
	{ name = "AddRedNormal", sizeX = nil, sizeY = nil },
	{ name = "AngarFlayButton", sizeX = nil, sizeY = nil },
	{ name = "BonusItem", sizeX = nil, sizeY = nil },
	{ name = "ButtonEmpty", sizeX = 128, sizeY = 30 },
	{ name = "ColorBack", sizeX = nil, sizeY = nil },
	{ name = "ColorBox", sizeX = nil, sizeY = nil },
	{ name = "ContextTooltipStatStar", sizeX = nil, sizeY = nil },
	{ name = "CornerCrossHighlight", sizeX = nil, sizeY = nil },
	{ name = "CornerCrossNormal", sizeX = nil, sizeY = nil },
	{ name = "CornerCrossPressed", sizeX = nil, sizeY = nil },
	{ name = "CycleLeft", sizeX = nil, sizeY = nil },
	{ name = "CyclePointer", sizeX = nil, sizeY = nil },
	{ name = "CycleRight", sizeX = nil, sizeY = nil },
	{ name = "DeskCardFace", sizeX = nil, sizeY = nil },
	{ name = "DeskCardFace-104", sizeX = 104, sizeY = 104 },
	{ name = "DeskInspectNormal-57", sizeX = 57, sizeY = 57 },
	{ name = "DeskInspectNormal-104", sizeX = 104, sizeY = 104 },
	{ name = "DeskInspectNormalF-57", sizeX = 57, sizeY = 57 },
	{ name = "DeskInspectNormalF-104", sizeX = 104, sizeY = 104 },
	{ name = "DeskSearchNormal-57", sizeX = 57, sizeY = 57 },
	{ name = "DeskSearchNormal-104", sizeX = 104, sizeY = 104 },
	{ name = "DeskTokenDeckGolden-64", sizeX = 64, sizeY = 64 },
	{ name = "DeskTokenDeckGolden-104", sizeX = 104, sizeY = 104 },
	{ name = "empty", sizeX = nil, sizeY = nil },
	{ name = "Empty_Tiled", sizeX = 104, sizeY = 104 },
	{ name = "Exp", sizeX = nil, sizeY = nil },
	{ name = "FastButton", sizeX = nil, sizeY = nil },
	{ name = "Frame104", sizeX = 104, sizeY = 104 },
	{ name = "FrameRed", sizeX = 104, sizeY = 104 },
	{ name = "GoldenCorner", sizeX = nil, sizeY = nil },
	{ name = "Ice4", sizeX = nil, sizeY = nil },
	{ name = "MarkHighlight", sizeX = 128, sizeY = 128 },
	{ name = "NamePlateFrame", sizeX = nil, sizeY = nil },
	{ name = "NamePlateFrameFR", sizeX = nil, sizeY = nil },
	{ name = "NamePlateFrameFR-104", sizeX = 104, sizeY = 104 },
	{ name = "NoMark", sizeX = 128, sizeY = 128 },
	{ name = "RacePlateSelected", sizeX = nil, sizeY = nil },
	{ name = "RacePlateSelectedFR", sizeX = nil, sizeY = nil },
	{ name = "RacePlateSelectedFR-104", sizeX = 104, sizeY = 104 },
	{ name = "Shield", sizeX = nil, sizeY = nil },
	{ name = "TitanToken", sizeX = nil, sizeY = nil },
	{ name = "TokenBattleStation", sizeX = nil, sizeY = nil },
	{ name = "Will", sizeX = nil, sizeY = nil },
--- from prototypes
	{ name = "ButtonRegular1-Disabled", sizeX = 128, sizeY = 30 },
	{ name = "ButtonRegular1-Highlighted", sizeX = 128, sizeY = 30 },
	{ name = "ButtonRegular1-Normal", sizeX = 128, sizeY = 30 },
	{ name = "ButtonRegular1-Pressed", sizeX = 128, sizeY = 30 },
	{ name = "CheckBox1-Stone", sizeX = 25, sizeY = 23 },
	{ name = "CheckBox1-StoneChecked", sizeX = 25, sizeY = 23 },
	{ name = "CheckBox1-StoneHighlight", sizeX = 25, sizeY = 23 },
	{ name = "ButtonRegular2-Highlighted", sizeX = 128, sizeY = 30 },
	{ name = "Header-Original", sizeX = 222, sizeY = 44 },

	{ name = "ButtonB", sizeX = 128, sizeY = 30 },
	{ name = "ButtonB1", sizeX = 128, sizeY = 30 },
	{ name = "ButtonBBrown", sizeX = 128, sizeY = 30 },
	{ name = "ButtonRed", sizeX = 128, sizeY = 30 },
	{ name = "FrameBBlue2", sizeX = 200, sizeY = 200 },
	{ name = "FrameBW1", sizeX = 104, sizeY = 104 },
	{ name = "FrameCardFaceGold", sizeX = 200, sizeY = 200 },
	{ name = "FrameStone1", sizeX = 200, sizeY = 200 },
	{ name = "FrameBlueH", sizeX = 200, sizeY = 200 },
	{ name = "FrameDeskCardBackL200", sizeX = 200, sizeY = 200 },
	{ name = "FrameDeskCardBackL104", sizeX = 104, sizeY = 104 },
	{ name = "ButtonDeskCardBackL", sizeX = 128, sizeY = 30 },
	{ name = "ButtonBlueO", sizeX = 128, sizeY = 30 },

	{ name = "FrameMain2", sizeX = 200, sizeY = 200 },
	{ name = "DeskTokenDeckGoldenT2-104", sizeX = 104, sizeY = 104 },
	{ name = "FrameBBlue2T2", sizeX = 200, sizeY = 200 },
	{ name = "FrameMain2T2", sizeX = 200, sizeY = 200 },
	{ name = "FrameStone1T2", sizeX = 200, sizeY = 200 },
	{ name = "ContextUse", sizeX = 64, sizeY = 64 },
	{ name = "PortalGreen", sizeX = 32, sizeY = 32 },
	{ name = "PortalRed", sizeX = 32, sizeY = 32 },

	{ name = "ButtonBlue", sizeX = 128, sizeY = 30 },
	{ name = "ButtonNBlue", sizeX = 128, sizeY = 30 },
	{ name = "ButtonNGreen", sizeX = 128, sizeY = 30 },
	{ name = "ButtonNRed", sizeX = 128, sizeY = 30 },
	{ name = "ButtonNWhite", sizeX = 128, sizeY = 30 },
	{ name = "CheckboxAnoNormal", sizeX = 37, sizeY = 37 },
	{ name = "CheckboxAnoNormalHighlighted", sizeX = 37, sizeY = 37 },
	{ name = "CheckboxAnoSelected", sizeX = 37, sizeY = 37 },
	{ name = "CheckboxAnoSelectedHighlighted", sizeX = 37, sizeY = 37 },
	{ name = "CircleBr", sizeX = 101, sizeY = 101 },
	{ name = "CircleBr0", sizeX = 101, sizeY = 101 },
	{ name = "CircleBrW", sizeX = 101, sizeY = 101 },
	{ name = "Circle", sizeX = 44, sizeY = 44 },
	{ name = "CheckC0", sizeX = 32, sizeY = 32 },
	{ name = "SlotBlink", sizeX = 64, sizeY = 64 },
	{ name = "ItemMallBannerHighlight", sizeX = 128, sizeY = 128 },
	{ name = "hideth1", sizeX = 200, sizeY = 200 },
	{ name = "hideth1B", sizeX = 200, sizeY = 200 },
	{ name = "CoinGold", sizeX = nil, sizeY = nil },
	{ name = "CoinCopper", sizeX = nil, sizeY = nil },
	{ name = "CoinSilver", sizeX = nil, sizeY = nil },

	{ name = "MailIconHollow", sizeX = 43, sizeY = 43 },
	{ name = "MailIconOpened", sizeX = 46, sizeY = 46 },
	{ name = "MailIconUnread", sizeX = 46, sizeY = 46 },
	{ name = "BorderLight", sizeX = 94, sizeY = 94 },

	{ name = "BorderSilv1", sizeX = 82 , sizeY = 82 },
	{ name = "BorderSilv1f", sizeX = 104 , sizeY = 104 },
	{ name = "BorderSilv2", sizeX = 82 , sizeY = 82 },
	{ name = "BorderSilv2f", sizeX = 104 , sizeY = 104 },
	{ name = "droplet1", sizeX = 32, sizeY = 32 },
	{ name = "IMWorldChat", sizeX = 64, sizeY = 64 },
	{ name = "Trumpet", sizeX = 64, sizeY = 64 },

	{ name = "BorderSilv1b", sizeX = 54, sizeY = 54 },
	{ name = "iconUnknown", sizeX = 32, sizeY = 32 },
	
	{ name = "ButtonBlueNormal", sizeX = 128, sizeY = 30 },
	{ name = "CheckBSpFrame", sizeX = 104, sizeY = 104 },

	
--	{ name = "", sizeX = nil, sizeY = nil },
	}

end

function getWorldTextutes()
	return makeTextures()
end